# 应用服务 WEB 访问端口
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
      username: root
      password: 1103
  mybatis:
    mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: warn
    com.wanglei: info
  file:
    path: log/blog-pro.log

server:
  port: 8081